# Pengenalan Pandas DataFrame

In [ ]:
import pandas as pd


In [ ]:
# List Buah (string)
list_buah = [ 'jeruk', 'pepaya', 'mangga','rambutan', 'leci', 'nanas', 'manggis']

# List Berat Buah (integer)
list_berat = [50,800,150,10,2,100,70]

# Membuat dataframe menggunakan Dua Buah List dengan fungsi zip
df = pd.DataFrame(list(zip(list_buah, list_berat)),
                  columns = ['Nama Buah', 'Berat Buah'])            
df

Nama Buah  Berat Buah
0     jeruk          50
1    pepaya         800
2    mangga         150
3  rambutan          10
4      leci           2
5     nanas         100
6   manggis          70

In [ ]:
# List Multidimensi (Nama, Usia)
lst = [['Bejo', 25], ['Ari', 30],
       ['Asep', 26], ['Richard', 22]]

df = pd.DataFrame(lst, columns =['Nama', 'Usia'])
df

Nama  Usia
0     Bejo    25
1      Ari    30
2     Asep    26
3  Richard    22

In [ ]:
mobil = {'Type Mobil': ['Honda Civic', 'Toyota Corolla', 'Ford Focus', 'Audi A4'], 
         'Harga(USD)': [22000,25000,27000,23000]}
         
df = pd.DataFrame(mobil)
df

Type Mobil  Harga(USD)
0     Honda Civic       22000
1  Toyota Corolla       25000
2      Ford Focus       27000
3         Audi A4       23000

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df_super_store = pd.read_csv('/Super-Store-Dataset.csv')
df_super_store.head()

order_id  order_date customer_id    segment         category  \
0  CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
1  CA-2016-152156   11/8/2016    CG-12520   Consumer        Furniture   
2  CA-2016-138688   6/12/2016    DV-13045  Corporate  Office Supplies   
3  US-2015-108966  10/11/2015    SO-20335   Consumer        Furniture   
4  US-2015-108966  10/11/2015    SO-20335   Consumer  Office Supplies   

  sub_category     sales  quantity    profit  
0    Bookcases  261.9600         2   41.9136  
1       Chairs  731.9400         3  219.5820  
2       Labels   14.6200         2    6.8714  
3       Tables  957.5775         5 -383.0310  
4      Storage   22.3680         2    2.5164

In [ ]:
df_pilkada = pd.read_excel('/datasetpilkadadki.xlsx')
df_pilkada.head()

Id Sentiment Pasangan Calon  \
0   1  negative     Agus-Sylvi   
1   2  negative     Agus-Sylvi   
2   3  negative     Agus-Sylvi   
3   4  negative     Agus-Sylvi   
4   5  negative     Agus-Sylvi   

                                          Text Tweet  
0  Banyak akun kloning seolah2 pendukung #agussil...  
1  #agussilvy bicara apa kasihan yaa...lap itu ai...  
2  Kalau aku sih gak nunggu hasil akhir QC tp lag...  
3  Kasian oh kasian dengan peluru 1milyar untuk t...  
4  Maaf ya pendukung #AgusSilvy..hayo dukung #Ani...

In [ ]:
import numpy as np

Membuat Array NumPy

In [ ]:
list_1 = [1,2,3,4,5]
arr_1 = np.array([list_1])
arr_1

array([[1, 2, 3, 4, 5]])

In [ ]:
print(np.zeros((2,5)))      # membuat array dengan nilai 0 dengan shape (5,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.ones((5,3)))       # membuat array dengan nilai 1 dengan shape (5,5)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.arange(1, 10, 2))  # arange(start, stop, stop)

[1 3 5 7 9]


In [ ]:
print(np.linspace(1, 10, 4))  # linspace(start, stop, number)

[ 1.  4.  7. 10.]


In [ ]:
print(np.logspace(1, 10, 2))  # logspace(start, stop, number)

[1.e+01 1.e+10]


In [ ]:
print(np.full((2,2), 4))  # membuat array matriks dengan shape (2,2) dengan elemen 99

[[4 4]
 [4 4]]


In [ ]:
A = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(A)

print(np.full_like(A,4)) 

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [ ]:
print(np.random.rand(4,2)) # random decimal numbers

[[0.03545536 0.16204246]
 [0.24196735 0.17744271]
 [0.78336771 0.92376833]
 [0.30924006 0.230552  ]]


In [ ]:
print(np.random.randint(-4,8, size=(3,3))) # random integer values

[[ 6 -2  3]
 [ 3  7  1]
 [-3  1  4]]


In [ ]:
print(np.identity(5)) # membuat matriks identitas

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
arr = np.array([[1,2,3]])   # membuat matriks dengan pengulangan array
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
